### ISSUE TITLE
-----BEGIN PUBLIC KEY-----

### ISSUE THREAD

**Issue by 510290848** [p11-glue/p11-glue#20]
![1000005649](https://user-images.githubusercontent.com/106413787/371759128-0b74867e-f6b9-46d8-bbbb-4f4f3a6072b6.png)
![1000002378](https://user-images.githubusercontent.com/106413787/371759131-27aab97a-a505-4bde-9822-413b180764dd.png)
              -----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0Hxv3MkkZbMrKtIs6np9
ccP4OwGBkNhIvhPjcQP48hbbascv5RqsOquQGrYSD2ZrE/kbkRdkIcoHEeTZLif+
bDKFZFI7o5x0H92o9/GSvxHJhQ8mkmvwxD7lssGShwZEm8WG+U7BZqUV/gGmCDqe
9W8H8Fq2B0ck8IXjbQ4Zz+JlyV/NHZTZcs69plFiLKh4N6GYVftOVwSomh0bbypP
OB9WnLC7RC9a2LRrhtf8sqa2rRFmtyMMfgFFzLMzS+w+1K4+QLnWP1gKQVzaFnzk
pnwKPrqbGFYbRztIVEWbs8jPYlLkGb8ME4C84YVtQgbQcbyisU/VW3wUGkhT+J0k
xwIDAQAB
-----END PUBLIC KEY-----

_Originally posted by @510290848 in https://github.com/p11-glue/p11-kit/issues/482#issuecomment-2380632340_

**Comment by ZoltanFridrich** [comment]
Closing as spam
